### PR TITLE
Add Rails 5 support

### PR DESCRIPTION
**Pull request by hlascelles**
This adds Rails 5 support. It constitutes:

1. Ensuring only existing Error classes are configured
1. Adding a Rails 5 Appraisal
1. Removing Airbrake 4 
1. Adding gem lockfiles (which [is now recommended](https://bundler.io/v1.3/rationale.html#checking-your-code-into-version-control)).

This expands on [the work](https://github.com/LevoLeague/egregious/commit/023f0a46bb7744a9525fa81faeb01417c3bc7580) of @dwbutler at LevoLeague.

### CODE REVIEW

**Comment by hlascelles** [comment]
@rx, is this what you were expecting for the PR?

**Comment by jonseaberg** [comment]
@rx Sorry to bump this.  Wondering if there is anything I can do to help move it along.

**Comment by joehorsnell** [comment]
@rx - this PR would be very useful for our Rails 5 migration, so your review would be much appreciated - thanks.

**Comment by hlascelles** [comment]
@rx, would you mind if I created a `egregious-rails5` gem for now? Or if there is something I can change on the PR, I can do that?

**Comment by paul110** [comment]
@rx a review for this would indeed be very useful in order to upgrade to Rails 5. Thanks.

**Pull request closed without merging**
